algoritmo "Exercício 17 - Lista de exercício 2"


var
   senha:inteiro
inicio
      //Entrada
      escreval("Este programa verifica a validade de uma senha.")
      escreval("Entre com a sua senha: ")
      leia(senha)
      
      //Processamento
      se (senha = 4531) entao
         escreval("SENHA VÁLIDA.")
      senao
         escrevaL("ERRO, SUA SENHA É INVÁLIDA.")
      fimse
      
      
fimalgoritmo
