algoritmo "Exercício 11 - Lista de exercício 1"

var
   area,diagma,diagme:real
inicio
      // Entrada
      escreval("Este programa calcula a área de um losango.")
      escreval("Entre com a diagonal maior: ")
      leia(diagma)
      escreval("Entre com a diagonal menor: ")
      leia(diagme)


      //Processamento

      area <- (diagma * diagme) /2


      //Saída
      escreval("A área do losango é: ",area:3:2)


fimalgoritmo
