algoritmo "Exercício 17 - Lista de exercícios 1"

var
    celsius:inteiro
    f:real
inicio
      //Entrada
      escreval("Este é um conversor de graus Celsius para Fahrenheit: ")
      escreval("Entre com a temperatura em celsius: ")
      leia(celsius)


      //Processamento
      f <- 180 * (celsius + 32) / 100


      //Saída
      escreval("A temperatura em Fahrenheit é: ",f:3:1,"ºF")


fimalgoritmo


