algoritmo "Exercício 3 - Lista de exercício 1"

var
   num1,num2,divis:inteiro

inicio
      // Entrada
      escreval("Este programa tem a função de receber dois valores e dividir o 1º pelo 2º.")
      escreval("Entre com o 1º número: ")
      leia(num1)
      escreval("Entre com o 2º número: ")
      leia(num2)

      //Processamento

      divis <- (num1 \ num2)

      //Saída
      escreval("O resultado da divisão é: ",divis)
      
fimalgoritmo
