algoritmo "Exercício 1 - Lista de exercício 1"

var
   num1,num2,subt:real
   
inicio
      // Entrada
      escreval("Este programa tem a função de receber dois valores e subtrair o 1º pelo 2º.")
      escreval("Entre com o 1º número: ")
      leia(num1)
      escreval("Entre com o 2º número: ")
      leia(num2)
      
      //Processamento
      
      subt <- num1 - num2
      
      //Saída
      escreval("O resultado da subtração é: ",subt)
      
fimalgoritmo
