algoritmo "Exercício 7 - Lista de exercício 1"

var
   peso,a,b:real
inicio
      // Entrada
      escreval("Este programa irá receber o peso de uma pessoa e calcular.")
      escreval("Entre com o peso: ")
      leia(peso)

      //Processamento

      a <- peso +  (15 / 100)
      b <- peso -  (20 / 100)

      //Saída
      escreval("Se a pessoa engordar 15% ela terá: ",a:3:2)
      escreval("Se a pessoa emagreer 20% ela terá: ",b:3:2)
      
fimalgoritmo
