GO
USE ECOMMERCE;

CREATE TABLE TB_CLIENTE(
	CLIENTE_ID INT IDENTITY NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID),
	CONSTRAINT CK_CLIENTE CHECK(SEXO IN ('F','M'))
);

CREATE TABLE TB_CLIENTE_TELEFONE(
	TELEFONE_ID INT IDENTITY PRIMARY KEY NOT NULL,
	NUMERO VARCHAR(9) NOT NULL,
	TIPO VARCHAR(15) NOT NULL,
	CLIENTE_ID INT NOT NULL,
	CONSTRAINT FK_TBCLIENTE_TELEFONE FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTE (CLIENTE_ID)

);

CREATE TABLE CLIENTE_ENDERECO(
	ENDERECO_ID INT IDENTITY PRIMARY KEY NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	TIPO_LOGRADOURO VARCHAR(7) NOT NULL,
	LOGRADOURO VARCHAR(40) NOT NULL,
	NUMERO VARCHAR(4) NOT NULL,
	COMPLEMENTO VARCHAR(40),
	BAIRRO VARCHAR(20) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	CLIENTE_ID INT NOT NULL,
	CONSTRAINT FK_TBCLIENTE_ENDERECO FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTE (CLIENTE_ID)
);


CREATE TABLE TB_CATEGORIA(
	CATEGORIA_ID INT IDENTITY PRIMARY KEY  NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	CATEGORIA_PAI_ID INT NOT NULL,
	CONSTRAINT FK_TB_CATEGORIA_CATEGORIAPAI FOREIGN KEY (CATEGORIA_PAI_ID) REFERENCES TB_CATEGORIA (CATEGORIA_ID)
);

CREATE TABLE TB_PRODUTO_IMAGEM(
	IMAGEM_ID INT IDENTITY PRIMARY KEY NOT NULL,
	URL VARCHAR(50) NOT NULL,
	LARGURA DECIMAL NOT NULL,
	ALTURA DECIMAL NOT NULL,
	TITULO VARCHAR(40) NOT NULL,
	PRODUTO_ID INT NOT NULL,
);

CREATE TABLE TB_PRODUTO(
	PRODUTO_ID INT IDENTITY PRIMARY KEY NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	PRECO DECIMAL(10,2) NOT NULL,
	DESCRICAO VARCHAR(50),
	QUANTIDADE INT NOT NULL,
	CATEGORIA_ID INT NOT NULL,
	PRODUTO_IMAGEM_ID INT NOT NULL,
	CONSTRAINT FK_TB_PRODUTO_TB_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA (CATEGORIA_ID),
	CONSTRAINT FK_TB_PRODUTO_TB_PRODUTO_IMAGEM FOREIGN KEY (PRODUTO_IMAGEM_ID) REFERENCES TB_PRODUTO_IMAGEM (IMAGEM_ID)
);


CREATE TABLE TB_PEDIDO(
	PEDIDO_ID INT IDENTITY PRIMARY KEY NOT NULL,
	STATUS_ID INT NOT NULL,
	DATA DATE NOT NULL,
	VALOR_FRETE DECIMAL(10,2) NOT NULL,
	VALOR_TOTAL DECIMAL(10,2) NOT NULL,
	CLIENTE_ID INT NOT NULL,
	CODIGO_RASTREIO VARCHAR(20) NOT NULL,
	ENDERECO_ID INT NOT NULL,
);

CREATE TABLE TB_STATUS(
	STATUS_ID INT IDENTITY PRIMARY KEY NOT NULL,
	PEDIDO_ID INT NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	CONSTRAINT FK_TB_STATUS FOREIGN KEY (PEDIDO_ID) REFERENCES TB_PEDIDO (PEDIDO_ID)
);

CREATE TABLE TB_ITEM_PEDIDO(
	PRODUTO_ID INT NOT NULL,
	PEDIDO_ID INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	SUBTOTAL DECIMAL(10,2) NOT NULL,

	CONSTRAINT PK_TB_ITEM_PEDIDO PRIMARY KEY(PRODUTO_ID,PEDIDO_ID),
	CONSTRAINT FK_TB_ITEM_PEDIDO_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES TB_PRODUTO (PRODUTO_ID),
	CONSTRAINT FK_TB_ITEM_PEDIDO_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES TB_PEDIDO (PEDIDO_ID)
);

CREATE TABLE TB_TRACKING(
	MOVIMENTACAO_ID INT IDENTITY PRIMARY KEY NOT NULL,
	PEDIDO_ID INT NOT NULL,
	STATUS_MOVIMENTACAO VARCHAR(10) NOT NULL,
	DATA_HORA DATETIME NOT NULL,

	CONSTRAINT FK_TBTRACKING FOREIGN KEY (PEDIDO_ID) REFERENCES TB_PEDIDO (PEDIDO_ID)

);

CREATE TABLE TB_TIPO_PAGAMENTO(
	PEDIDO_ID INT IDENTITY NOT NULL,
	TIPO VARCHAR(20),
	STATUS_PAGAMENTO VARCHAR(20),

	CONSTRAINT FK_TB_TIPO_PAGAMENTO FOREIGN KEY (PEDIDO_ID) REFERENCES TB_PEDIDO (PEDIDO_ID),
	CONSTRAINT PK_TB_TIPO_PAGAMENTO PRIMARY KEY (PEDIDO_ID)
);

ALTER TABLE TB_PRODUTO_IMAGEM ADD
	CONSTRAINT FK_TB_PRODUTO_IMAGEM_PROD FOREIGN KEY (PRODUTO_ID) REFERENCES TB_PRODUTO (PRODUTO_ID);
	
ALTER TABLE TB_PEDIDO ADD
	CONSTRAINT FK_TB_PEDIDO_STATUS FOREIGN KEY (STATUS_ID) REFERENCES TB_STATUS (STATUS_ID),
	CONSTRAINT FK_TB_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTE (CLIENTE_ID),
	CONSTRAINT FK_TB_PEDIDO_ENDERECO FOREIGN KEY (ENDERECO_ENTREGA_ID) REFERENCES CLIENTE_ENDERECO (ENDERECO_ID);

ALTER TABLE TB_CLIENTE_TELEFONE ADD
	CONSTRAINT CK_TBCLIENTE_TELEFONE CHECK(TIPO IN('RESIDENCIAL', 'COMERCIAL', 'CELULAR'));



