CREATE DATABASE EMPRESA
GO
USE EMPRESA;

CREATE TABLE EMPREGADOS(
	CODFUN INT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	NUM_DEPEND VARCHAR(8) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	COD_DEPTO INT NOT NULL,
	COD_CARGO INT NOT NULL,
	DATA_ADMISSAO DATE NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	SINDICALIZADO VARCHAR(5) NOT NULL,
	OBS VARCHAR(50)
);

CREATE TABLE DEPENDENTES(
	CODFUN INT NOT NULL,
	CODDEP INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE TABELA_DEP(
	COD_DEPTO INT PRIMARY KEY,
	DEPTO VARCHAR(50) NOT NULL
);

CREATE TABLE TABELA_CAR(
	COD_CARGO INT PRIMARY KEY,
	CARGO VARCHAR(20) NOT NULL,
	SALARIO_INIC DECIMAL(10,2) NOT NULL
);


ALTER TABLE EMPREGADOS ADD
	CONSTRAINT FK_TABELADEPARTAMENTO FOREIGN KEY(COD_DEPTO) REFERENCES TABELA_DEP,
	CONSTRAINT FK_TABELACARGO FOREIGN KEY(COD_CARGO) REFERENCES TABELA_CAR,
	CONSTRAINT CK_EMPREGADOS CHECK (SALARIO < 0);
	
ALTER TABLE DEPENDENTES ADD
	CONSTRAINT FK_TABELAEMPREGADOS FOREIGN KEY(CODFUN) REFERENCES EMPREGADOS,
	CONSTRAINT PK_DEPENDETES PRIMARY KEY(CODDEP,CODFUN);