GO
--1
USE PEDIDOS;

--2
SELECT COD_PRODUTO, DESCRICAO,PRECO_CUSTO, PRECO_VENDA, (PRECO_VENDA - PRECO_CUSTO) AS LUCRO FROM PRODUTOS;

--3
SELECT COD_PRODUTO, DESCRICAO, (QTD_REAL * PRECO_CUSTO) AS 'TOTAL INVESTIDO' FROM PRODUTOS;

--4
SELECT NUM_PEDIDO, NUM_ITEM, COD_PRODUTO, PR_UNITARIO, QUANTIDADE, DESCONTO, (PR_UNITARIO  * QUANTIDADE * (1 - DESCONTO/100)) AS 'VALOR DE ITEM' FROM ITENSPEDIDO;

--5
SELECT COD_PRODUTO, DESCRICAO, PRECO_CUSTO, PRECO_VENDA, (QTD_REAL * (PRECO_VENDA - PRECO_CUSTO)) AS 'LUCRO ESTIMADO EM REAIS' FROM PRODUTOS;

--6
SELECT COD_PRODUTO, DESCRICAO, PRECO_CUSTO, PRECO_VENDA, (PRECO_VENDA - PRECO_CUSTO) AS 'LUCRO REAIS', ((100 *(PRECO_VENDA - PRECO_CUSTO)/PRECO_CUSTO)) AS 'LUCRO PERCENTUAL' FROM PRODUTOS WHERE PRECO_CUSTO > 0;

--7
SELECT (QTD_REAL - QTD_MINIMA) FROM PRODUTOS WHERE QTD_REAL < QTD_MINIMA;

--8
SELECT * FROM PRODUTOS WHERE QTD_REAL > 5000;

--9
SELECT * FROM PRODUTOS WHERE PRECO_VENDA < 0.50;

--10
SELECT * FROM PEDIDOS WHERE VLR_TOTAL > 15000;

--11
SELECT * FROM PRODUTOS WHERE QTD_REAL >= 500 AND QTD_REAL <= 1000;

--12
SELECT * FROM PEDIDOS WHERE VLR_TOTAL >= 15000 AND VLR_TOTAL <= 25000;

--13
SELECT * FROM PRODUTOS WHERE QTD_REAL > 5000 AND COD_TIPO = 6;

--14
SELECT * FROM PRODUTOS WHERE QTD_REAL > 5000 OR COD_TIPO = 6;

--15
SELECT * FROM PEDIDOS WHERE VLR_TOTAL < 100 OR VLR_TOTAL > 100000;

--16
SELECT * FROM PRODUTOS WHERE QTD_REAL < 500 OR QTD_REAL > 1000;

--17
SELECT * FROM CLIENTES WHERE ESTADO = 'SP';

--18
SELECT * FROM CLIENTES WHERE ESTADO IN ('MG','RJ');

--19
SELECT * FROM CLIENTES WHERE ESTADO IN ('SP','MG','RJ');

--20
SELECT * FROM VENDEDORES WHERE NOME = 'LEIA';

--21
SELECT * FROM CLIENTES WHERE NOME LIKE 'BRINDES%';

--22
SELECT * FROM CLIENTES WHERE NOME LIKE '%BRINDES';

--23
SELECT * FROM CLIENTES WHERE NOME LIKE '%BRINDES%';

--24
SELECT * FROM PRODUTOS WHERE DESCRICAO LIKE 'CANETA%';

--25
SELECT * FROM PRODUTOS WHERE DESCRICAO LIKE '%SPECIAL%';

--26
SELECT * FROM PRODUTOS WHERE DESCRICAO LIKE '%GOLD';

--27
SELECT * FROM CLIENTES WHERE NOME LIKE '_A%';

--28
SELECT * FROM PRODUTOS WHERE COD_PRODUTO LIKE '_0%';

--29
SELECT * FROM PRODUTOS WHERE COD_PRODUTO LIKE '__A%';

--30
SELECT * FROM PEDIDOS WHERE YEAR (DATA_EMISSAO) < 2006;

--31
SELECT * FROM PEDIDOS WHERE YEAR (DATA_EMISSAO) = 2006 AND MONTH (DATA_EMISSAO) >= 01 AND MONTH (DATA_EMISSAO) <= 06;

--32
SELECT * FROM PEDIDOS WHERE YEAR (DATA_EMISSAO) = 2006 AND MONTH (DATA_EMISSAO) = 01 OR YEAR (DATA_EMISSAO) = 2006 AND MONTH (DATA_EMISSAO) = 06;

--33
SELECT * FROM PEDIDOS WHERE CODVEN = 1 AND YEAR (DATA_EMISSAO) = 2006 AND MONTH (DATA_EMISSAO) = 01;

--34
SELECT * FROM PEDIDOS WHERE YEAR(DATA_EMISSAO) = 2006 AND MONTH (DATA_EMISSAO) = 01 AND DATEPART (WEEKDAY, DATA_EMISSAO) = 06;
