CREATE DATABASE PEDIDOS_VENDAS;
GO
USE PEDIDOS_VENDAS;

CREATE TABLE UNIDADES(
	CODIGO_DA_UNIDADE INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_DA_UNIDADE CHARACTER(40) NOT NULL 
);	

INSERT INTO UNIDADES
(NOME_DA_UNIDADE)
VALUES
('PEÇAS'),
('METROS'),
('QUILOGRAMAS'),
('DÚZIAS'),
('PACOTE'),
('CAIXA');

CREATE TABLE CATEGORIAS(
	CODIGO_DA_CATEGORIA INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_DA_UNIDADE CHARACTER(40) NOT NULL 
);

INSERT INTO CATEGORIAS
(NOME_DA_UNIDADE)
VALUES
('MOUSE'),
('PEN-DRIVE'),
('MONITOR DE VÍDEO'),
('TECLADO'),
('CPU'),
('CABO DE REDE');

CREATE TABLE PRODUTOS(
	CODIGO_DO_PRODUTO INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_DO_PRODUTO CHARACTER(40) NOT NULL,
	CODIGO_DA_UNIDADE_DE_MEDIDA INT, --FK
	CODIGO_DA_CATEGORIA INT, --FK
	QUANTIDADE_EM_ESTOQUE NUMERIC NOT NULL,
	QUANTIDADE_MINIMA NUMERIC NOT NULL,
	PRECO_DE_CUSTO NUMERIC NOT NULL,
	PRECO_DE_VENDA NUMERIC NOT NULL,
	CARACTERISTICAS_TECNICAS VARCHAR NULL

	CONSTRAINT PK_COD_UNIDADE_MEDIDA_PRODUTOS FOREIGN KEY(CODIGO_DA_UNIDADE_DE_MEDIDA) REFERENCES UNIDADES(CODIGO_DA_UNIDADE),
	CONSTRAINT PK_COD_CATEGORIA_PRODUTOS FOREIGN KEY(CODIGO_DA_CATEGORIA) REFERENCES CATEGORIAS(CODIGO_DA_CATEGORIA)
);

INSERT INTO PRODUTOS
(NOME_DO_PRODUTO, CODIGO_DA_UNIDADE_DE_MEDIDA, CODIGO_DA_CATEGORIA, QUANTIDADE_EM_ESTOQUE, QUANTIDADE_MINIMA, PRECO_DE_CUSTO, PRECO_DE_VENDA, CARACTERISTICAS_TECNICAS)
VALUES
('CANETA AZUL', '1', '1', '150', '40', '0.5', '0.75', ''),
('CANETA VERDE', '1', '1', '50', '40', '0.5', '0.75', ''),
('CANETA VERMELHA', '1', '1', '80', '35', '0.5', '0.75', ''),
('LÁPIS', '1', '1', '400', '80', '0.5', '0.8', ''),
('RÉGUA', '1', '1', '40', '10', '1', '1.5', '');
